### ISSUE TITLE
Error on write

### ISSUE THREAD

**Issue by hovnatan** [neoclide/coc-python#48]
If a save a python file (unfortunately cannot share) two times in a row with `:w` I get the error in screenshot:
![2019-05-29-115136_1920x1080_scrot](https://user-images.githubusercontent.com/8426582/58539554-a6b8f800-8208-11e9-95ee-e30f3fcc80d5.png)

If you really need it I can try reproducing the issue in a public file.

**Comment by chemzqm** [comment]
Fixed on master of coc.nvim.

**Comment by hovnatan** [comment]
@chemzqm now I get 
![2019-05-29-120420_539x55_scrot](https://user-images.githubusercontent.com/8426582/58540166-dc121580-8209-11e9-812e-1cbf49408ea2.png)

**Comment by chemzqm** [comment]
Please use `:messages` to get full messages.

**Comment by hovnatan** [comment]
![2019-05-29-120902_1659x394_scrot](https://user-images.githubusercontent.com/8426582/58540472-7e31fd80-820a-11e9-8f4e-1fc2d4434fec.png)

**Comment by chemzqm** [comment]
It was fixed on 1.1.10, upgrade coc-python.

**Comment by hovnatan** [comment]
@chemzqm I still get it after `:CocUpdateSync`. How can I check the version?

**Comment by chemzqm** [comment]
`:CocList extensions`

**Comment by hovnatan** [comment]
@chemzqm still have the same error with 
![2019-05-29-121452_919x49_scrot](https://user-images.githubusercontent.com/8426582/58540922-6c048f00-820b-11e9-8246-16bf20d49223.png)

**Comment by chemzqm** [comment]
Fixed

**Comment by hovnatan** [comment]
@chemzqm  Still errors with 1.1.12 :( Now I have this:
![2019-05-29-122837_1640x297_scrot](https://user-images.githubusercontent.com/8426582/58541824-64de8080-820d-11e9-89ac-99d4239e5321.png)

**Comment by chemzqm** [comment]
Try upgrade to 1.1.13

**Comment by hovnatan** [comment]
Nope :) 
![2019-05-29-124647_1528x252_scrot](https://user-images.githubusercontent.com/8426582/58543091-c69fea00-820f-11e9-9f93-08babe63f369.png)

**Comment by hovnatan** [comment]
@chemzqm ok, no errors in 1.1.14. Thanks!

**Comment by chemzqm** [comment]
Try 1.1.14, if still not work, I don't know how to fix.

**Comment by hovnatan** [comment]
@chemzqm ok, no errors in 1.1.14. Thanks!
