### ISSUE TITLE
Rope Variable/Method Extraction not working

### ISSUE THREAD

**Issue by steven-lang** [neoclide/coc-python#66]
Using `:CocAction` -> `Extract Variable [python.simpleRefactor]` in the following content: 
```python
a = "Hello" + " " + "World"
# -------------^-----------
# Cursor here  |
```
results in the following error message:
```
[<FrameSummary file refactor.py, line 294 in watch>, <FrameSummary file refactor.py, line 279 in _process_request>, <FrameSumma
ry file refactor.py, line 219 in _extractVariable>, <FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/
base/project.py, line 211 in __init__>])
```

Minimal `.vimrc`:
```
call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}

call plug#end()

" if hidden is not set, TextEdit might fail.
set hidden

" Extensions
let g:coc_global_extensions=['coc-python']
```

**Comment by chemzqm** [comment]
Should be bug of coc-python.

**Comment by chemzqm** [comment]
Fixed, also you have to save the buffer and select variable name for this action to work.

**Comment by steven-lang** [comment]
Still doesn't work for me. I'm now getting the following error:

```
<FrameSummary file refactor.py, line 294 in watch
<FrameSummary file refactor.py, line 279 in _process_request
<FrameSumma ry file refactor.py, line 223 in _extractVariable
<FrameSummary file refactor.py, line 117 in refactor
<FrameSummary file r efactor.py, line 163 in onRefactor
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/refactor/extrac t.py, line 69 in get_changes
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/refactor/extract.py, line 216 in extract
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/refactor/extract.py, line 245 in _collect_info
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/refactor/extract.py, line 258 in _find_matches
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/refactor/similarfinder.py, line 101 in get_matches
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/refactor/similarfinder.py, line 111 in _get_matched_asts
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/refactor/similarfinder.py, l ine 119 in _create_pattern
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/base/ast.py, line 21 in parse>
```

**Comment by chemzqm** [comment]
You have to save the buffer and select exact variable name

**Comment by steven-lang** [comment]
The buffer was saved. What do you mean by "select exact variable name"?
I've tried a few different things:

Note: `|` indicates cursor, `[...]` indicates selection

1) 
```python
a = "|Hello" + "World"
```

2) 
```python
a = "[Hello]" + "World"
```

3) 
```python
a = ["Hello"] + "World"
```

All of them lead to the error above.

For executing the refactor command I run `:CocAction` and select `1 Extrat Variable [python.simpleRefactor]`.

**Comment by chemzqm** [comment]
You have to select the variable name like `a`, it doesn't support extract string.

**Comment by steven-lang** [comment]
Why would I want to extract `a`? 

The vs-code extension supports the extraction:
```python
a = ["Hello"] + "World"
```
ends up in
```python
newvariable496 = "Hello"
a = newvariable496 + "World"
```

**Comment by chemzqm** [comment]
Fixed now.

**Comment by steven-lang** [comment]
Still not working. Stacktrace is now:

```
<FrameSummary file refactor.py, line 294 in watch
<FrameSummary file refactor.py, line 279 in _process_request
<FrameSummary file refactor.py, line 223 in _extractVariable
<FrameSummary file refactor.py, line 117 in refactor
<FrameSummary file refactor.py, line 163 in onRefactor
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/refactor/extract.py, line 69 in get_changes
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/refactor/extract.py, lin e 216 in extract
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/refactor/extract.py, line 245 in _collect_info
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/refactor/extract.py, line 258 in _find_matches
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/refactor/similarfinder.py, line 101 in get_matches
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/refactor/similarfinder.py, line 111 in _g et_matched_asts
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/refactor/similarfinder.py, line 119 in _create_patter n
<FrameSummary file /home/tak/test-coc/env/lib/python3.6/site-packages/rope/base/ast.py, line 21 in parse>
```

**Comment by svermeulen** [comment]
Why is this closed?  I can't get anything to do with rope to work either, with similar errors

**Comment by steven-lang** [comment]
It's not fixed, but @chemzqm thought it was and closed it. It was never reopened again and I didn't bother to open another issue.

**Comment by mks1508** [comment]
@steven-lang @svermeulen you can't make **rope** work like that
you need go Visual Mode to select region, then call CocAction
so you will need put this into **vimrc**:

```vim
xmap <leader>a  <Plug>(coc-codeaction-selected)
```

Then
```python
a = "Hello" + "World"
```
Go Visual Mode -> select **"Hello"** ->  **\<leader\>a**  -> Extract Variable
Result:
```python
newvariable954 = "Hello"
a = newvariable954 + "World"
```

**Comment by jkroes** [comment]
I see a lot of separate issues from the past year related to rope rename and extraction. I'm in the same boat as @svermeulen. Nothing in rope has worked for me, and I've tried installing different combinations of rope, Python, and neovim. No idea how to debug the error messages.
